version: "3.9"

services:
  proxypool:
    container_name: proxypool
    ports:
      - "8080:8080"
    build:
      context: .
    environment:
      - GIN_MODE=release
      - PROXYPOOL_LOG_LEVEL=info
      - PROXYPOOL_PORT=8080
      - PROXYPOOL_STORAGE=redis
      - PROXYPOOL_REDIS.HOST=redis
      - PROXYPOOL_REDIS.PORT=6379
      - PROXYPOOL_REDIS.DB=0
      - PROXYPOOL_QIYUN_APIKEY=
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:latest
    command: redis-server --appendonly yes